# Generated by Django 4.0.5 on 2022-06-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('q1', models.CharField(choices=[('Reincarnation', '1'), ('Go to a holy place', '2'), ('Nothing', '3')], max_length=200)),
                ('q2', models.CharField(max_length=10)),
                ('q3', models.CharField(max_length=10)),
                ('q4', models.CharField(max_length=10)),
                ('q5', models.CharField(max_length=10)),
                ('q6', models.CharField(max_length=10)),
                ('q7', models.CharField(max_length=10)),
                ('q8', models.CharField(max_length=10)),
                ('q9', models.CharField(max_length=10)),
                ('q10', models.CharField(max_length=10)),
                ('q11', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'User response',
            },
        ),
    ]
