# Generated by Django 4.0.5 on 2022-06-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='q1',
            field=models.CharField(choices=[('1', 'Reincarnation'), ('2', 'Go to a holy place'), ('3', 'Nothing')], max_length=200, verbose_name='What do you believe happens after you die?'),
        ),
    ]
